### ISSUE TITLE
no ipa output when using relative path for .ipa file in resign-ipa step

### ISSUE THREAD

**Issue by 50chickens** [bitrise-steplib/steps-resign-ipa#3]
im using bitrise cli and when i specify the ipa_file location parameter using a relative path, the step reports success, but no file is output. when using an absolute path it works fine. 

step output: 

Configs:
- ipa_path: xxx.ipa
- distribution_type: Appstore
- team_id: xxx
- app_id_prefix: 

Resigning ipa `xxx.ipa` with team id `xxx`
Resigned ipa is available at: ./xxx-Appstore-resigned.ipa

The resigned IPA path is now available in the Environment Variable: $BITRISE_RESIGNED_IPA_PATH'
|                                                                              |
+----+--------------------------------------------------------------+----------+
| ✅  | resign-ipa@1.1.0                                             | 13 sec   |
+----+--------------------------------------------------------------+----------+

+------------------------------------------------------------------------------+
|                               bitrise summary                                |
+----+--------------------------------------------------------------+----------+
|    | title                                                        | time (s) |
+----+--------------------------------------------------------------+----------+
| ➡  | certificate-and-profile-installer@1.7.0                      | 0.66 sec |
+----+--------------------------------------------------------------+----------+
| ✅  | resign-ipa@1.1.0                                             | 13 sec   |
+----+--------------------------------------------------------------+----------+
| Total runtime: 14 sec                                                        |
+------------------------------------------------------------------------------+

INFO[23:31:12]  
INFO[23:31:12] Submitting anonymized usage information...  
INFO[23:31:12] For more information visit:  
INFO[23:31:12] https://github.com/bitrise-core/bitrise-plugins-analytics/blob/master/README.md 
xxx-Mac-3:codesigndoc_exports $ ls -la xxx-Appstore-resigned.ipa
ls: xxx-Appstore-resigned.ipa: No such file or directory

**Comment by viktorbenei** [comment]
Thanks for reporting the issue! We'll fix it ASAP!

**Comment by birmacher** [comment]
Issue will be fixed in the following PR: #6

**Comment by birmacher** [comment]
I'm closing the issue. The PR was merged and we will release the step in 1-2 hours. 
If you hit the same issue, please let us know!
