### ISSUE TITLE
.ipa signature not valid after resigning.

### ISSUE THREAD

**Issue by 50chickens** [bitrise-steplib/steps-resign-ipa#4]
after resigning the .ipa using the resign-ipa step, the resulting .ipa file does not pass the certificate (unresigned .ipa is ok however).

**Comment by birmacher** [comment]
Hi @50chickens!

Just replied to the same question here: https://github.com/bitrise-steplib/steps-resign-ipa/issues/5#issuecomment-255206003

I'll merge together the two tickets, but if you follow the details in the comment, you should be able to fix the re-signing process.

**Comment by birmacher** [comment]
Closing ( duplicate of #5 ). Let's continue the discussion there! 👍
