### ISSUE TITLE
Error uploading to the app store: ERROR ITMS-90046: "Invalid Code Signing Entitlements

### ISSUE THREAD

**Issue by johnpeb** [bitrise-steplib/steps-resign-ipa#5]
After resigning we're seeing this error:

> ERROR ITMS-90046: "Invalid Code Signing Entitlements. Your application bundle's signature contains code signing entitlements that are not supported on iOS. Specifically, value '*' for key 'com.apple.developer.associated-domains' in 'Payload/yyy.app/yyy' is not supported."

My situation is almost exactly the same a https://github.com/fastlane/fastlane/issues/768

> I have 3 values configured in Xcode for associated-domains and the checkbox is checked on the App in iTunes Connect. Any ideas?

**Comment by viktorbenei** [comment]
Thanks for reporting @johnpeb !

@birmacher this one's for you ;)

**Comment by birmacher** [comment]
Thanks! 🙂

I believe this is the same issue as the following here: #4.
We are currently looking into the issue and will update you guys with our progress.

**Comment by birmacher** [comment]
Hi @johnpeb!

Can you please double check the profile that you are re-signing with? I believe it holds a \* identifier and that is the one that causes the issue. If you change the profile to a new one that has an explicit id, you will be good to go.

If it's still happening, please ping me on intercom on bitrise.io and we will figure it out!  ( messagebox on the bottom right corner )

**Comment by johnpeb** [comment]
@birmacher sorry for the delay in responding. Unfortunately we've switched over to directly signing with the final profile so I can't take another look. Feel free to close this if it's working for you.

**Comment by aortich** [comment]
John you're a filthy piece of shit.
