### ISSUE TITLE
Codesign fails with error Error: Payload/MyApp.app: invalid resource directory (directory or signature have been modified)

### ISSUE THREAD

**Issue by kensykora** [bitrise-steplib/steps-resign-ipa#9]
I am trying to Re-Sign a Xamarin app, and when I try to re-sign it, I get this error:

```
 +------------------------------------------------------------------------------+
| (12) resign-ipa@1.2.0                                                        |
+------------------------------------------------------------------------------+
| id: resign-ipa                                                               |
| version: 1.2.0                                                               |
| collection: https://github.com/bitrise-io/bitrise-steplib.git                |
| toolkit: bash                                                                |
| time: 2017-01-17T14:17:12-08:00                                              |
+------------------------------------------------------------------------------+
|                                                                              |
Installing Gemfile
Configs:
  * ipa_path: /Users/vagrant/deploy/MyApp.ipa
  * distribution_type: InHouse
  * team_id: XXXXXXXXX
  * app_id_prefix: 

Resigning ipa `/Users/vagrant/deploy/MyApp.ipa` with team id `XXXXXXXXXX`
security: SecPolicySetValue: One or more parameters passed to a function were not valid.
security: SecPolicySetValue: One or more parameters passed to a function were not valid.
security: SecPolicySetValue: One or more parameters passed to a function were not valid.
security: SecPolicySetValue: One or more parameters passed to a function were not valid.
security: SecPolicySetValue: One or more parameters passed to a function were not valid.
sh: line 1:  3221 Trace/BPT trap: 5       /usr/bin/codesign -f -s "iPhone Distribution: The MyAppCompany (XXXXXXXXX)" --entitlements entitlements.plist "Payload/MyApp.app" 2> /dev/null
Error: Payload/MyApp.app: invalid resource directory (directory or signature have been modified)

Failed to resign ipa
/private/var/folders/90/5stft2v13fb_m_gv3c8x9nwc0000gn/T/bitrise065182626/step_src/resigner.rb:31:in `block in resign'
/private/var/folders/90/5stft2v13fb_m_gv3c8x9nwc0000gn/T/bitrise065182626/step_src/resigner.rb:16:in `chdir'
/private/var/folders/90/5stft2v13fb_m_gv3c8x9nwc0000gn/T/bitrise065182626/step_src/resigner.rb:16:in `resign'
/var/folders/90/5stft2v13fb_m_gv3c8x9nwc0000gn/T/bitrise065182626/step_src/step.rb:27:in `<main>'
```

It's unclear what I need to do in order to resolve this, can you offer any insight? I'm trying to sign it with profiles and certificates that I installed using Fastlane Match. I have 2 fastlane tasks in my workflow that install an AdHoc and AppStore certificate, and I'd like to use those to resign the app. If I choose a different build configuration that uses the AdHoc / AppStore certificates/provisioning profiles, the signing works correctly, but I'd like to produce both an AdHoc and AppStore build in a single run (and was hoping to use this tool to do that)

Any help would be appreciated. Thanks!

**Comment by godrei** [comment]
Hi @kensykora sorry for my late response!

Could you please try to use `Export iOS and tvOS Xcode archive` step instead of this one?
Export archive uses `xcodebuild` build tool to export an .ipa file from .xcarchive, this is the recommended way to generate .ipa file.

If you are using `Xcode Archive for iOS` step to generate your first ipa file, just set `Export the generated archive?` input to `yes`, this case the step will export the generated xcarchive, into `BITRISE_XCARCHIVE_PATH` env var, which is the default value of `Export iOS and tvOS Xcode archive` step's `iOS or tvOS archive path` input.

**Comment by godrei** [comment]
Closing as we did not receive a reply - @kensykora please let us know if we can help with anything and we'll reopen this issue!

**Comment by jasonfma** [comment]
@godrei I'm running into the same error. The way I use this step is:
1) Generate `.ipa` with `Xcode Archive for iOS` with manual code signing
2) Modify configuration file inside `.ipa`
3) Use `resign ipa` step here to resign the `.ipa`  <--- failed with error

I'm trying a bunch of different things - including not even modifying the `.ipa`. Still getting this error.

Stack: macOS Sierra 10.12 xcode 8 (Xamarin stable with xcode 8)

**Comment by jasonfma** [comment]
Opened up a PR to fix this issue. Additionally, I needed to change the `Certificate and profile installer` to use `$HOME/Library/Keychains/login.keychain-db` as the keychain path.
